### ISSUE TITLE
best practices for gene annotation

### ISSUE THREAD

**Issue by nclowell** [OARS-SAFS/resources#14]
Looking for guidance on best practices for gene annotation. I have two RADseq data sets, one with some molecular resources (genome, transcriptome), one without. For each I have a subset of SNPs that are putatively adaptive, and I'm interested in finding out what genes they might be associated with.

In asking around, some folks use Blast2Go, some blast against the UniProt database, some use the simple online blast tool with their fasta file, etc. 

My questions are:
- is there a "best" tool? if the "best" tool is context specific, what are the cases for using each tool?
- (when) should one include flanking regions of a locus?
- when you don't have molecular resources, do you search only closely related taxa? and if so, generally how close (like genus? family?)

Guessing this is a mostly Roberts Lab question - any thoughts @sr320 @shellytrigg @yaaminiv @kubu4 @grace-ac @laurahspencer ? Also happy to be pointed to somewhere to read if there's a good synthesis resource.

Thanks!

**Comment by sr320** [comment]
Good Q!
All of the suggestions are blast, so that is certainly what I would recommend. 
I suggest running it locally as you have more control. 
I would recommend using the UniProt database - (Swiss-Prot) - _Manually annotated_

Yes, flanking regions would be good to check.
Regarding taxa, UniProt database - (Swiss-Prot), has a good representation, and allows you to go further into GO information.
If there are no hits, I would recommend going more specific and blast against all nucleotides sequences in NCBI.

**Comment by nclowell** [comment]
Thanks for your response!

From what I gather, use blast locally with the UniProt database, and if that doesn't work, blast to all of NCBI. Let me know if that's not right!

And, are their norms around the size of flanking regions? Like, is a flanking region generally 50-100bp on their side or more like 1000bp?

**Comment by sr320** [comment]
> From what I gather, use blast locally with the UniProt database, and if that doesn't work, blast to all of NCBI. Let me know if that's not right!

Correct,  I would also run against all of NCBI locally. 

Re Flanking - I would start with 1000bp flanking, but expand it if no hits to maybe 10k.

**Comment by nclowell** [comment]
Thanks!

**Comment by yaaminiv** [comment]
@sr320 covered most of it, but I've always been taught to `blast` to the Uniprot-SwissProt database, then match the blast results with gene ontology terms to better group the genes SNPs/loci of interest are in/near. I made [this tutorial](https://github.com/eimd-2019/tutorials/blob/master/2019-07-09-Uniprot-blastx-Tutorial.md) for the class I TA'ed over the summer that walks through some of the steps.

For flanking, you can check out `bedtools`! [`flankBed`](https://bedtools.readthedocs.io/en/latest/content/tools/flank.html) lets you add flanks to various features. Another useful tool if you're interested in which SNPs are in genes/near genes is [`closestBed`](https://bedtools.readthedocs.io/en/latest/content/tools/closest.html).

**Comment by nclowell** [comment]
Thanks @yaaminiv!
