### ISSUE TITLE
Anyone have experience using "Teams"

### ISSUE THREAD

**Issue by sr320** [OARS-SAFS/resources#3]
![Teams_·_Open_and_Reproducible_Science](https://user-images.githubusercontent.com/4442039/69467845-9b213680-0d3e-11ea-9a3c-f5fca86a257c.jpg)

**Comment by mdscheuerell** [comment]
Hey @sr320, my wife uses teams with her group and says that it largely helps with keeping people straight on different projects/repos (eg, one of the benefits is that once teams are established, you can assign them to repos en masse).

**Comment by sr320** [comment]
thanks!
