### ISSUE TITLE
port 22 issue while transferring files to hyak

### ISSUE THREAD

**Issue by nclowell** [OARS-SAFS/resources#5]
Hauser lab mates and I are trying to rsync some files onto the Roberts lab hyak node. We are already logged in to hyak, and using your [wiki](https://github.com/RobertsLab/hyak_mox/wiki/File-Transfers). We get this error about port 22:

![image](https://user-images.githubusercontent.com/22554275/69583339-85ef1680-0f8f-11ea-95ac-aac47bd34cdf.png)

Do you know where we went wrong? Do we need to swap public SSH keys first? Or use SFTP?

**Comment by sr320** [comment]
Sorry about the bot post 😺 - still working out the 🐛 s.

I am going to guess that this refers to the fact your 205.... machine has port 22 blocked.

You could try the reverse where you are logged onto your 205.... machine and rsync other direction.

(helpful hint - you can just copy and paste terminal output as code in markdown in an issue) - no image necessary.

**Comment by kubu4** [comment]
First thing to to test is whether or not you can SSH from Mox to that computer:

From your Mox login node: 

`ssh ubuntu@205.175.118.227`

When you do that, what happens? Do you get prompted for a password? Have you been able to SSH from Mox to that computer before?

Also, I'm a bit surprised that the username listed above is "ubuntu". Is your target computer actually a Linux computer? Is it Windows 10 running Ubuntu?

**Comment by nclowell** [comment]
Thanks @sr320 we'll try the reverse rsync and see if that helps. And also try @kubu4's rec to ssh from mox to the computer.

Yea that machine's username is indeed ubuntu 😬 it was not my doing. It's a linux virtual machine running on windows.

**Comment by kubu4** [comment]
>  It's a linux virtual machine running on windows.

Well, I think this will complicate things.

I'd guess that port 22 is closed (as was mentioned above). You'll likely have to make this change in the Windows firewall settings.

Some internet searching should get you pointed in the right direction.

Also, you'll want to verify that the `openssh` program is installed on the Linux VM and also confirm that it's actually running.

**Comment by nclowell** [comment]
> > It's a linux virtual machine running on windows.
> 
> Well, I think this will complicate things.

It might, but I also work on a linux virtual machine and Steven hasn't had any problems rysncing my files to hyak.

I used a VM on Google Cloud a few weeks ago, and got a similar port 22 error before the SSH connection was properly set up. I didn't change my firewall settings. But I'll look into it!! First I'll check if ``openssh`` is installed on that computer. Thanks @kubu4!

**Comment by kubu4** [comment]
> similar port 22 error before the SSH connection was properly set up

This implies that you fixed an error like this previously. Have you taken the same steps on this computer that you did on the Google Cloud VM?

**Comment by kubu4** [comment]
>  First I'll check if openssh is installed on that computer.

Specifically, run the following:

`sudo dpkg -l openssh-server`

You should get an output like:

```
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  openssh-server                                1:7.2p2-4ubuntu2.8          amd64                       secure shell (SSH) server, for secure access from remote machines
```

(Don't worry if you get some weird other messages above those lines).

**Comment by nclowell** [comment]
> > similar port 22 error before the SSH connection was properly set up
> 
> This implies that you fixed an error like this previously. Have you taken the same steps on this computer that you did on the Google Cloud VM?

I haven't yet, but that's why I asked at the beginning whether we need to swap SSH public keys first in order for rsync to work. When Steven has come in to help us and rysnced our files, we couldn't remember if he first established an SSH connection between our computers and hyak (and we were both under the impression that he didn't need to, or that setting up the rsync created the ssh access). The tutorial I followed for Google Cloud implied that I had to. Should I go ahead and add the hyak public SSH key to my computer and vice versa?

@EleniLPetrou can chime in about whether ``openssh-server`` is installed using your suggestion

**Comment by sr320** [comment]
again - the simpler solution would be when you are logged onto `ubuntu` rsync with mox using ssh. That is what I did.

**Comment by EleniLPetrou** [comment]
Hi y'all! Here is an update of what I have tried so far and what has worked:

1. I was able to use rsync from my ubuntu@ubuntu machine (you don't like the name? :) ) to transfer files to hyak, no problem, using this:

```
rsync --archive --progress --verbose path/bcftools.sh uwnetid@mox.hyak.uw.edu:/gscratch/scrubbed/uwnetid
```

2. I was able to use sftp to move files from my computer to mox using this script:

```
sftp -oPort=22 uwnetid@mox.hyak.uw.edu
put *.txt
```

I also followed @kubu4 advice (thank you!) to check whether openssh was installed on my beloved ubuntu@ubuntu using ``sudo dpkg -l openssh-server``


 This is the output:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  openssh-server <none>       <none>       (no description available)

```

I will try installing openssh next, and let you know how that goes. Thank you for all the help!!

**Comment by kubu4** [comment]
> rsync with mox using ssh

@sr320 Isn't that what is shown in the initial post?

**Comment by sr320** [comment]
no she was logged into mox, doing it from mox.

What I was suggesting is what @EleniLPetrou got to work 

> I was able to use rsync from my ubuntu@ubuntu machine (you don't like the name? :) ) to transfer files to hyak, no problem, using this:

**Comment by kubu4** [comment]
Oh, oh, I see. I read that sentence differently.

**Comment by kubu4** [comment]
> I will try installing openssh next, and let you know how that goes.

@EleniLPetrou : No need. You should be all set for moving files to/from Mox.

Plus, the subsequent process to set up your computer for _receiving_ SSH connections is kind of a pain...

**Comment by nclowell** [comment]
Thanks so much @kubu4 and @sr320! I think we're all good now.

Just as a heads-up, the examples on the [wikipage on File Transfers](https://github.com/RobertsLab/hyak_mox/wiki/File-Transfers) are for using ``rsync`` when logged into Mox (I think!). This might snag future users if they're anything like us 😅
