### ISSUE TITLE
rsync error: permission denied for some files & dirs

### ISSUE THREAD

**Issue by nclowell** [OARS-SAFS/resources#8]
I'm moving files from hyak to my computer using rsync, most files moved fine. But I got the following error:

```
rsync: send_files failed to open "/gscratch/scrubbed/sr320/cragig_wdn6/reference.fasta.original.gz": Permission denied (13)
logfiles/
logfiles/trim_reports/
raw.vcf/

sent 9,768 bytes  received 109,102 bytes  4,851.84 bytes/sec
total size is 253,714,179,834  speedup is 2,134,383.61
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1677) [generator=3.1.3]
```

I tried rerunning the rsync command and I get the same error. @kubu4 or @sr320 has this ever happened to you? Do you know why permission is being denied to specific files and folders, but not the rest?

**Comment by kubu4** [comment]
Can you please post the command you ran to initiate`rsync`?

**Comment by nclowell** [comment]
```
rsync --archive --verbose --progress nclowell@198.48.92.25:/gscratch/scrubbed/sr320/cragig_wdn6/* /mnt/hgfs/E/dD_cragig_mox_20191205/
```

**Comment by kubu4** [comment]
The answer is that you don't have read permissions on that file. Only the owner (`sr320`) can read that file:

```shell 
ls -l /gscratch/scrubbed/sr320/cragig_wdn6/reference.fasta.original.gz

-rw------- 1 sr320 hyak-coenv 0 Dec  5 02:00 /gscratch/scrubbed/sr320/cragig_wdn6/reference.fasta.original.gz
```

As far as _why_, who knows...

If you want that file, you'll need @sr320 to change permissions so that other people can read it.

**Comment by sr320** [comment]
@kubu4 I could also just transfer to `/gscratch/scrubbed/nclowell`?

**Comment by kubu4** [comment]
I don't think that will alter the permissions.

**Comment by sr320** [comment]
@nclowell should be good now...

for reference I ran  `chmod -R 777 cragig_wdn6`

**Comment by nclowell** [comment]
Worked - thank you!!
